@startuml
start
:User enters add lesson command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid command])
    :Parse command arguments;
    if () then ([module code exists in model])
        if () then ([lesson does not exist in model])
            :Add lesson to TrackIt@NUS;
            :Save updated lesson list to trackIter.json;
            :Show success message;
        else ([else])
            :Throw duplicate lesson error;
        endif
    else ([else])
        :Throw module does not exist error;
    endif
else ([else])
    :Shows an invalid command message;
endif
stop
@enduml
