@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":AddLessonCommand" as AddLessonCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant ":TrackIter" as TrackIter MODEL_COLOR
end box

[-> AddLessonCommand : execute(m)
activate AddLessonCommand

AddLessonCommand -> Model : hasModule(l.getCode())
activate Model

Model -> TrackIter : hasModule(l.getCode())

deactivate Model

AddLessonCommand -> Model : hasLesson(l)
activate Model

Model -> TrackIter : hasLesson(l)

deactivate Model

AddLessonCommand -> Model : addLesson(l)
activate Model

Model -> TrackIter : addLesson(l)

deactivate Model

create CommandResult
AddLessonCommand -> CommandResult
activate CommandResult

CommandResult --> AddLessonCommand : r
deactivate CommandResult

[<--AddLessonCommand : r
deactivate AddLessonCommand

@enduml
