@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":AddModuleCommand" as AddModuleCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant ":TrackIter" as TrackIter MODEL_COLOR
end box

[-> AddModuleCommand : execute(m)
activate AddModuleCommand

'hasModule
AddModuleCommand -> Model : hasModule(code)
activate Model
Model -> TrackIter : hasModule(code)
TrackIter --> Model : result
Model --> AddModuleCommand : result
deactivate Model
'end

'canAddMoreModule
AddModuleCommand -> Model : canAddMoreModule()
activate Model
Model -> Model : getFilteredModuleList()
activate Model
Model --> Model : moduleList
deactivate Model
Model --> AddModuleCommand : result
deactivate Model
'end

'addModule
AddModuleCommand -> Model : addModule(t)
activate Model
Model -> TrackIter : addModule(t)
deactivate Model
'end


create CommandResult
AddModuleCommand -> CommandResult
activate CommandResult

CommandResult --> AddModuleCommand : r
deactivate CommandResult

[<--AddModuleCommand : r
deactivate AddModuleCommand

@enduml
