@startuml
start
:User enters add task command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid command])
    :Parse command arguments;
    if () then ([task does not exist in model])
        if () then ([task code is not present or code is present and exists in model])
            :Add task to TrackIt@NUS;
            :Save updated task list to trackIter.json;
            :Show success message;
        else ([else])
            :Throw module does not exist error;
        endif
    else ([else])
        :Throw duplicate task error;
    endif
else ([else])
    :Shows an invalid command message;
endif
stop
@enduml
