@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":AddTaskCommand" as AddTaskCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "t:Task" as task MODEL_COLOR
participant ":TrackIter" as TrackIter MODEL_COLOR
end box

[-> AddTaskCommand : execute(m)
activate AddTaskCommand

AddTaskCommand -> Model : hasTask(t)
activate Model

Model -> TrackIter : hasTask(t)
activate TrackIter

TrackIter --> Model
deactivate TrackIter

Model --> AddTaskCommand
deactivate Model

AddTaskCommand -> task : getCode()
activate task

task --> AddTaskCommand
deactivate task

AddTaskCommand -> Model : hasModule(t.getCode().get())
activate Model

Model -> TrackIter : hasModule(t.getCode().get())
activate TrackIter

TrackIter --> Model
deactivate TrackIter

Model --> AddTaskCommand
deactivate Model

AddTaskCommand -> Model : addTask(t)
activate Model

Model -> TrackIter : addTask(t)
activate TrackIter

TrackIter --> Model
deactivate TrackIter

Model --> AddTaskCommand
deactivate Model

create CommandResult
AddTaskCommand -> CommandResult
activate CommandResult

CommandResult --> AddTaskCommand : r
deactivate CommandResult

[<--AddTaskCommand : r
deactivate AddTaskCommand

@enduml
