@startuml
start
:User enters command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid command])
    :Parse command arguments;
    :Execute command;
    :Save updated modue/lesson/task/contact list to trackIter.json;
    :Show success message;
else ([else])
    :Shows an invalid command message;
endif
stop
@enduml
