@startuml
start
:User enters delete task command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid command])
    :Retrieve the last shown task list;
    if () then ([index provided is within range of last shown list])
        :Retrieve the task at the given index;
        :Delete the task;
        :Save updated task list to trackIter.json;
        :Show success message;
    else ([else])
        :Show invalid task index error message;
    endif
else ([else])
    :Shows an invalid command message;
endif
stop
@enduml
