@startuml
start
:User enters delete contact command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid command])
    :Retrieve the last shown contact list;
    if () then ([index provided is within range of last shown list])
        :Retrieve the contact at the given index;
        :Delete the contact;
        :Save updated contact list to trackIter.json;
        :Show success message;
    else ([else])
        :Show invalid contact index error message;
    endif
else ([else])
    :Shows an invalid command message;
endif
stop
@enduml
