@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":EditTaskCommand" as EditTaskCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "index:Index" as index MODEL_COLOR
participant ":TrackIter" as TrackIter MODEL_COLOR
end box

[-> EditTaskCommand : execute(m)
activate EditTaskCommand

EditTaskCommand -> Model : getFilteredTaskList()
activate Model

Model --> EditTaskCommand : lastShownList
deactivate Model

EditTaskCommand -> index : getZeroBased()

EditTaskCommand -> EditTaskCommand : createEditedTask(taskToEdit, editTaskDescriptor)
activate EditTaskCommand
EditTaskCommand --> EditTaskCommand : editedTask
deactivate EditTaskCommand

EditTaskCommand -> Model : setTask(taskToEdit, editedTask)
activate Model

Model -> TrackIter : setTask(taskToEdit, editedTask)


deactivate Model

create CommandResult
EditTaskCommand -> CommandResult
activate CommandResult

CommandResult --> EditTaskCommand : r
deactivate CommandResult

[<--EditTaskCommand : r
deactivate EditTaskCommand

@enduml
