

@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":Logic" as Logic LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "predicate:ContactHasTagPredicate" as ContactHasTagPredicate MODEL_COLOR
end box

[-> MainWindow : User click on a module tab
activate Logic

activate MainWindow
MainWindow -> Logic : getModuleContacts(code)

Logic -> Model : getModuleContacts(code)
activate Model


create ContactHasTagPredicate
note over ContactHasTagPredicate
predicate that returns true when if a contact
is associated with a module
end note
Model -> ContactHasTagPredicate : code
activate ContactHasTagPredicate
ContactHasTagPredicate --> Model : predicate
deactivate ContactHasTagPredicate

Model -> Model : updateFilteredContactList(predicate)
activate Model
deactivate Model

Model -> Model : getFilteredContactList()
activate Model
Model --> Model : contactList
deactivate Model

Model --> Logic : contactList
Logic --> MainWindow : contactList
deactivate Logic

[<- MainWindow : display to User
deactivate MainWindow

@enduml


