@startuml
!include style.puml
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTrackIter <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class TrackIter
Class ReadOnlyTrackIter
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Module {
Class UniqueModuleList
}

Package Lesson {
Class UniqueLessonList
}

Package Task {
Class UniqueTaskList
}

Package Contact {
Class UniqueContactList
}


}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TrackIter .up.|> ReadOnlyTrackIter

ModelManager .up.|> Model
Model .right.> ObservableList

ModelManager o--> "1" TrackIter
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

TrackIter *--> "1" UniqueLessonList
TrackIter *--> "1" UniqueModuleList
TrackIter *--> "1" UniqueContactList
TrackIter *--> "1" UniqueTaskList

@enduml
