@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR


package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class StatusBarFooter
Class CommandBox
Class SidePanel
Class Button

package UpcomingTab <<Rectangle>> {
'Class HiddenUpcomingTab #FFFFFF
}

package ContactTab <<Rectangle>> {
'Class HiddenContactTab #FFFFFF
}

package ModuleTab <<Rectangle>> {
'Class HiddenModuleTab #FFFFFF
}

package HelpTab <<Rectangle>> {
'Class HiddenHelpTab #FFFFFF
}
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow *-down-> StatusBarFooter
MainWindow *-down-> ResultDisplay
MainWindow *-down-> CommandBox
MainWindow *-down-> SidePanel
MainWindow *-down--> UpcomingTab
MainWindow *-down--> ContactTab
MainWindow *-down--> ModuleTab
MainWindow *-down--> HelpTab

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
StatusBarFooter --|> UiPart
UpcomingTab -down-|> UiPart
ContactTab -down-|> UiPart
ModuleTab -down-|> UiPart

SidePanel *-down-> Button
Button -> UiPart

Button ...> Model
UpcomingTab ...> Model
ContactTab ...> Model
ModuleTab ...> Model
UiManager -right-> Logic
MainWindow -left-> Logic

ModuleTab --> Logic
UpcomingTab --> Logic

Logic -[hidden]up- UI
ModuleTab -[hidden]left- ContactTab
ContactTab -[hidden]left- UpcomingTab
UpcomingTab -[hidden]left- SidePanel
SidePanel -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
