@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UpcomingTab <<Rectangle>>{

Class UpcomingPanel
Class UpcomingSectionDayCard
Class UpcomingSectionCard
Class LessonListPanel
Class TaskListPanel
Class OverdueFutureTaskCard
Class UpcomingTaskCard
Class UpcomingLessonCard
Class TaskCard
Class LessonCard

}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
MainWindow *--> UpcomingPanel

UpcomingPanel *--> UpcomingSectionDayCard
UpcomingPanel *--> UpcomingSectionCard

UpcomingSectionCard --> TaskListPanel
UpcomingSectionDayCard --> TaskListPanel
UpcomingSectionDayCard --> LessonListPanel

TaskListPanel --> OverdueFutureTaskCard
TaskListPanel --> UpcomingTaskCard
LessonListPanel --> UpcomingLessonCard

OverdueFutureTaskCard --|> TaskCard
UpcomingTaskCard --|> TaskCard
UpcomingLessonCard --|> LessonCard

TaskCard ..> Model
LessonCard ..> Model


'DayCard -down-|> UiPart
'CalendarSectionCard -down-|> UiPart

UpcomingPanel ----> Logic
UpcomingSectionDayCard ----> Logic
UpcomingSectionCard ---> Logic

'UpcomingTab -[hidden]left- Logic
'UpcomingTab -[hidden]left- Model


@enduml
